services:
  - type: web
    name: linkedin-scraper
    env: python
    plan: free
    buildCommand: |
      # Update and install dependencies
      apt-get update
      apt-get install -y chromium chromium-driver
      # Install Python dependencies
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
